sudo: required
services: 
 - docker
before_install:
 - docker build -t DHANYAVARGHESE/react-test -f ./client/Dockerfile.dev ./client
script:
 - docker run DHANYAVARGHESE/react-test npm test -- --coverage
after_sucess:
 - docker build -t DHANYAVARGHESE/multi-client ./client
 - docker build -t DHANYAVARGHESE/multi-nginx ./nginx
 - docker build -t DHANYAVARGHESE/multi-worker ./worker
 - docker build -t DHANYAVARGHESE/multi-server ./server  


//Login to docker CLI

 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

//Push our code to docker hub
 - docker push DHANYAVARGHESE/multi-client
 - docker push DHANYAVARGHESE/multi-nginx
 - docker push DHANYAVARGHESE/multi-worker
 - docker push DHANYAVARGHESE/multi-server


